apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  labels:
    app: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - name: mysql-server
        image: mysql:5.7
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
           name: mysqlpass
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-pv-claim
      volumes:
      - name: mysql-pv-claim
        persistentVolumeClaim:
          claimName: mysql-pv-claim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  labels:
    app: mysql-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-client
  template:
    metadata:
      labels:
        app: mysql-client
    spec:
      containers:
      - name: mysql-client
        image: adminer
        ports:
        - containerPort: 8080