kind: Service
apiVersion: v1
metadata:
  name: mysql-server
spec:
  selector:
    app: mysql-server
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306

---

kind: Service
apiVersion: v1
metadata:
  name: client-port
spec:
  selector:
    app: mysql-client
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080